=== AntaresSimulatorTeam/antares-xpansion/conception/output_example.schema.json
{
	"definitions": {},
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "https://example.com/object1591364010.json",
	"title": "Root",
	"type": "object",
	"required": [
		"begin",
		"end",
		"duration",
		"antares",
		"antares_xpansion",
		"options",
		"solution"
	],
	"optional": [
		"iterations"
	],
	"additionalProperties": false,
	"properties": {
		"begin": {
			"$id": "#root/begin",
			"title": "Begin",
			"type": "string",
			"default": "",
			"examples": [
				"datetime"
			],
			"pattern": "^.*$"
		},
		"end": {
			"$id": "#root/end",
			"title": "End",
			"type": "string",
			"default": "",
			"examples": [
				"datetime"
			],
			"pattern": "^.*$"
		},
		"duration": {
			"$id": "#root/duration",
			"title": "Duration",
			"type": "number",
			"default": "",
			"examples": [
				12.3
			],
			"pattern": "^.*$"
		},
		"antares": {
			"$id": "#root/antares",
			"title": "Antares",
			"type": "object",
			"required": [
				"version",
				"name"
			],
			"properties": {
				"version": {
					"$id": "#root/antares/version",
					"title": "Version",
					"type": "string",
					"default": "",
					"examples": [
						"version"
					],
					"pattern": "^.*$"
				},
				"name": {
					"$id": "#root/antares/name",
					"title": "Name",
					"type": "string",
					"default": "",
					"examples": [
						"study_name"
					],
					"pattern": "^.*$"
				}
			}
		},
		"antares_xpansion": {
			"$id": "#root/antares_xpansion",
			"title": "Antares_xpansion",
			"type": "object",
			"required": [
				"version"
			],
			"properties": {
				"version": {
					"$id": "#root/antares_xpansion/version",
					"title": "Version",
					"type": "string",
					"default": "",
					"examples": [
						"version"
					],
					"pattern": "^.*$"
				}
			}
		}
,
		"options": {
			"$id": "#root/options",
			"title": "options",
			"type": "object",
			"required": [
				"ACTIVECUTS",
				"AGGREGATION",
				"BASIS",
				"BOUND_ALPHA",
				"CSV_NAME",
				"DELETE_CUT",
				"GAP",
				"INPUTROOT",
				"LOG_LEVEL",
				"LOG_OUTPUT",
				"MASTER_METHOD",
				"MASTER_NAME",
				"MAX_ITERATIONS",
				"OUTPUTROOT",
				"RAND_AGGREGATION",
				"SLAVE_NUMBER",
				"SLAVE_WEIGHT",
				"SLAVE_WEIGHT_VALUE",
				"STRUCTURE_FILE",
				"THRESHOLD_AGGREGATION",
				"THRESHOLD_ITERATION",
				"TRACE",
				"XPRESS_TRACE"
			],
			"properties": {
				"ACTIVECUTS": {
					"$id": "#root/options/ACTIVECUTS",
					"title": "ACTIVECUTS",
					"type": "boolean",
					"default": "",
					"examples": [
						false
					]
				},
				"AGGREGATION": {
					"$id": "#root/options/AGGREGATION",
					"title": "AGGREGATION",
					"type": "boolean",
					"default": "",
					"examples": [
						false
					]
				},
				"BASIS": {
					"$id": "#root/options/BASIS",
					"title": "BASIS",
					"type": "boolean",
					"default": "",
					"examples": [
						true
					]
				},
				"BOUND_ALPHA": {
					"$id": "#root/options/BOUND_ALPHA",
					"title": "BOUND_ALPHA",
					"type": "boolean",
					"default": "",
					"examples": [
						true
					]
				},
				"CSV_NAME": {
					"$id": "#root/options/CSV_NAME",
					"title": "CSV_NAME",
					"type": "string",
					"default": "",
					"examples": [
						"benders_output_trace"
					],
					"pattern": "^.*$"
				},
				"DELETE_CUT": {
					"$id": "#root/options/DELETE_CUT",
					"title": "DELETE_CUT",
					"type": "boolean",
					"default": "",
					"examples": [
						false
					]
				},
				"GAP": {
					"$id": "#root/options/GAP",
					"title": "GAP",
					"type": "number",
					"default": "",
					"examples": [
						1e-06
					]
				},
				"INPUTROOT": {
					"$id": "#root/options/INPUTROOT",
					"title": "INPUTROOT",
					"type": "string",
					"default": "",
					"examples": [
						"."
					],
					"pattern": "^.*$"
				},
				"LOG_LEVEL": {
					"$id": "#root/options/LOG_LEVEL",
					"title": "LOG_LEVEL",
					"type": "integer",
					"default": "",
					"examples": [
						3
					]
				},
				"LOG_OUTPUT": {
					"$id": "#root/options/LOG_OUTPUT",
					"title": "LOG_OUTPUT",
					"type": "string",
					"default": "",
					"examples": [
						"COMMAND"
					],
					"pattern": "^.*$"
				},
				"MASTER_METHOD": {
					"$id": "#root/options/MASTER_METHOD",
					"title": "MASTER_METHOD",
					"type": "string",
					"default": "",
					"examples": [
						"SIMPLEX"
					],
					"enum": ["SIMPLEX", "BARRIER", "BARRIER_WO_CROSSOVER"]
				},
				"MASTER_NAME": {
					"$id": "#root/options/MASTER_NAME",
					"title": "MASTER_NAME",
					"type": "string",
					"default": "",
					"examples": [
						"master"
					],
					"pattern": "^.*$"
				},
				"MAX_ITERATIONS": {
					"$id": "#root/options/MAX_ITERATIONS",
					"title": "MAX_ITERATIONS",
					"type": "integer",
					"default": "",
					"examples": [
						-1
					]
				},
				"OUTPUTROOT": {
					"$id": "#root/options/OUTPUTROOT",
					"title": "OUTPUTROOT",
					"type": "string",
					"default": "",
					"examples": [
						"."
					],
					"pattern": "^.*$"
				},
				"RAND_AGGREGATION": {
					"$id": "#root/options/RAND_AGGREGATION",
					"title": "RAND_AGGREGATION",
					"type": "integer",
					"default": "",
					"examples": [
						0
					]
				},
				"SLAVE_NUMBER": {
					"$id": "#root/options/SLAVE_NUMBER",
					"title": "SLAVE_NUMBER",
					"type": "integer",
					"default": "",
					"examples": [
						-1
					]
				},
				"SLAVE_WEIGHT": {
					"$id": "#root/options/SLAVE_WEIGHT",
					"title": "SLAVE_WEIGHT",
					"type": "string",
					"default": "",
					"examples": [
						"CONSTANT"
					],
					"pattern": "^.*$"
				},
				"SLAVE_WEIGHT_VALUE": {
					"$id": "#root/options/SLAVE_WEIGHT_VALUE",
					"title": "SLAVE_WEIGHT_VALUE",
					"type": "number",
					"default": "",
					"examples": [
						1.0
					]
				},
				"STRUCTURE_FILE": {
					"$id": "#root/options/STRUCTURE_FILE",
					"title": "STRUCTURE_FILE",
					"type": "string",
					"default": "",
					"examples": [
						"structure.txt"
					],
					"pattern": "^.*$"
				},
				"THRESHOLD_AGGREGATION": {
					"$id": "#root/options/THRESHOLD_AGGREGATION",
					"title": "THRESHOLD_AGGREGATION",
					"type": "integer",
					"default": "",
					"examples": [
						0
					]
				},
				"THRESHOLD_ITERATION": {
					"$id": "#root/options/THRESHOLD_ITERATION",
					"title": "THRESHOLD_ITERATION",
					"type": "integer",
					"default": "",
					"examples": [
						0
					]
				},
				"TRACE": {
					"$id": "#root/options/TRACE",
					"title": "TRACE",
					"type": "boolean",
					"default": "",
					"examples": [
						true
					]
				},
				"XPRESS_TRACE": {
					"$id": "#root/options/XPRESS_TRACE",
					"title": "XPRESS_TRACE",
					"type": "integer",
					"default": "",
					"examples": [
						0
					]
				}
			}
		}
,
		"iterations": {
			"$id": "#root/iterations",
			"title": "Iterations",
			"type": "object",
			"required": [
				"1"
			],
			"properties": {
				"1": {
					"$id": "#root/iterations/1",
					"title": "1",
					"type": "object",
					"required": [
						"duration",
						"gap",
						"investment_cost",
						"operational_cost",
						"overall_cost",
						"relative_gap",
						"ub",
						"lb",
						"candidates"
					],
					"properties": {
						"duration": {
							"$id": "#root/iterations/1/duration",
							"title": "Duration",
							"type": "number",
							"default": "",
							"examples": [
								0.005
							]
						},
						"gap": {
							"$id": "#root/iterations/1/gap",
							"title": "gap",
							"type": "number",
							"default": "",
							"examples": [
								100015.15
							]
						},
						"investment_cost": {
							"$id": "#root/iterations/1/investment_cost",
							"title": "investment_cost",
							"type": "number",
							"default": "",
							"examples": [
								5955146100
							]
						},
						"operational_cost": {
							"$id": "#root/iterations/1/operational_cost",
							"title": "operational_cost",
							"type": "number",
							"default": "",
							"examples": [
								0.005
							]
						},
						"overall_cost": {
							"$id": "#root/iterations/1/overall_cost",
							"title": "overall_cost",
							"type": "number",
							"default": "",
							"examples": [
								0.005
							]
						},
						"relative_gap": {
							"$id": "#root/iterations/1/relative_gap",
							"title": "relative_gap",
							"type": "number",
							"default": "",
							"examples": [
								0.005
							]
						},
						"ub": {
							"$id": "#root/iterations/1/ub",
							"title": "ub",
							"type": "number",
							"default": "",
							"examples": [
								0.005
							]
						},
						"lb": {
							"$id": "#root/iterations/1/lb",
							"title": "lb",
							"type": "number",
							"default": "",
							"examples": [
								0.005
							]
						},
						"candidates": {
							"$id": "#root/iterations/1/candidates",
							"title": "candidates",
							"type": "array",
							"default": [],
							"items" : { "$ref" : "#/definitions/candidate_name" }
						}
					}
				}
			}
		},
		"solution": {
			"$id": "#root/solution",
			"title": "solution",
			"type": "object",
			"examples": [
				1
			],
			"default": 0,
			"required": [
				"gap",
				"investment_cost",
				"optimality",
				"values"
            ],
            "optional": [
                "operational_cost",
				"overall_cost",
				"iteration"
            ],
			"properties": {
				"gap": {
					"$id": "#root/solution/gap",
					"title": "gap",
					"type": "number",
					"default": "",
					"examples": [
						100015.15
					]
				},
				"investment_cost": {
					"$id": "#root/solution/investment_cost",
					"title": "investment_cost",
					"type": "number",
					"default": "",
					"examples": [
						5955146100
					]
				},
				"operational_cost": {
					"$id": "#root/solution/operational_cost",
					"title": "operational_cost",
					"type": "number",
					"default": "",
					"examples": [
						0.005
					]
				},
				"overall_cost": {
					"$id": "#root/solution/overall_cost",
					"title": "overall_cost",
					"type": "number",
					"default": "",
					"examples": [
						0.005
					]
				},
				"iteration": {
					"$id": "#root/solution/iteration",
					"title": "iteration",
					"type": "integer",
					"default": "",
					"examples": [
						2
					]
				},
				"optimality": {
					"$id": "#root/solution/optimality",
					"title": "optimality",
					"type": "boolean",
					"default": false,
					"examples": [
						false
					]
				},
				"values": {
					"$id": "#root/solution/values",
					"title": "values",
					"type": "object",
					"default": {},
					"additionalProperties": {
                    	"type": "number"
                    }
				}
			}
		}
	},
    "definitions": {
        "candidate_name": {
            "title": "Candidate",
            "type": "object",
            "required": [
                "name",
                "invest"
            ],
            "properties": {
                "name" : {
                    "title": "Name",
                    "type": "string",
                    "examples": [
                        "Candidate_A"
                    ]
                },
                "invest": {
                    "title": "Invest",
                    "type": "number",
                    "examples": [
                        1
                    ],
                    "default": 0
                }
            }
        }
    }
}

=== AntaresSimulatorTeam/antares-xpansion/conception/sequential_out_example.json
{
	"antares" : 
	{
		"name" : "0.0.0",
		"version" : "unknown"
	},
	"antares_xpansion" : 
	{
		"version" : "0.0.0"
	},
	"begin" : "01-07-2020 10:53:50",
	"duration" : 0.0,
	"end" : "01-07-2020 10:53:50",
	"iterations" : 
	{
		"1" : 
		{
			"candidates" : 
			[
				{
					"invest" : 0.0,
					"name" : "x"
				}
			],
			"duration" : 0.0018815430000000001,
			"gap" : 10000000004.0,
			"investment_cost" : 0.0,
			"lb" : -10000000000.0,
			"operational_cost" : 0.0,
			"overall_cost" : 0.0,
			"relative_gap" : 2500000001.0,
			"ub" : 4.0
		},
		"2" : 
		{
			"candidates" : 
			[
				{
					"invest" : 10.000000000000004,
					"name" : "x"
				}
			],
			"duration" : 0.0013298279999999999,
			"gap" : 16.000000000000007,
			"investment_cost" : 15.000000000000005,
			"lb" : -1.0000000000000018,
			"operational_cost" : 0.0,
			"overall_cost" : 15.000000000000005,
			"relative_gap" : 1.0666666666666667,
			"ub" : 15.000000000000005
		},
		"3" : 
		{
			"candidates" : 
			[
				{
					"invest" : 1.5,
					"name" : "x"
				}
			],
			"duration" : 0.0036349350000000002,
			"gap" : 0.0,
			"investment_cost" : 2.25,
			"lb" : 3.25,
			"operational_cost" : 0.0,
			"overall_cost" : 2.25,
			"relative_gap" : 0.0,
			"ub" : 3.25
		}
	},
	"options" : 
	{
		"ACTIVECUTS" : false,
		"AGGREGATION" : false,
		"BASIS" : true,
		"BOUND_ALPHA" : true,
		"CSV_NAME" : "benders_output_trace",
		"DELETE_CUT" : false,
		"GAP" : 9.9999999999999995e-07,
		"INPUTROOT" : ".",
		"LOG_LEVEL" : 3,
		"LOG_OUTPUT" : "COMMAND",
		"MASTER_METHOD" : "SIMPLEX",
		"MASTER_NAME" : "master",
		"MAX_ITERATIONS" : -1,
		"OUTPUTROOT" : ".",
		"RAND_AGGREGATION" : 0,
		"SLAVE_NUMBER" : -1,
		"SLAVE_WEIGHT" : "CONSTANT",
		"SLAVE_WEIGHT_VALUE" : 1.0,
		"STRUCTURE_FILE" : "structure.txt",
		"THRESHOLD_AGGREGATION" : 0,
		"THRESHOLD_ITERATION" : 0,
		"TRACE" : true,
		"XPRESS_TRACE" : 0
	},
	"solution" : 
	{
		"gap" : 0.0,
		"investment_cost" : 2.25,
		"iteration" : 3,
		"operational_cost" : 0.0,
		"optimality" : true,
		"overall_cost" : 2.25,
		"values" : 
		{
			"x" : 1.5
		}
	}
}
